### PR TITLE
Add support for 'nonce'

### LINKED ISSUE #1: nonce required in implicit grant type
The OpenID Connect spec requires the use of a nonce for the implicit grant type, see http://openid.net/specs/openid-connect-core-1_0.html#ImplicitAuthRequest

But it seems to be impossible to set it with this library.

### PR DESCRIPTION
**Pull request by cdevienne**
Fix #1

### CODE REVIEW

**Comment by cdevienne** [comment]
Hi @eamelink, could you review this patch?
Thanks

Christophe

**Comment by eamelink** [comment]
Hi, thanks for adding this! I'm trying to build an application that uses Google OpenID connect, and it requires the nonce to be there.

I've tried this branch, and ran into these things:
* The nonce should be read from the token, and not from the querystring when after the redirect.
* Google's login page breaks if the nonce contains odd characters (haven't figured out which characters classify as odd exactly. I've changed the random generator to use `Char.latin` instead of `Char.ascii`.
* The implementation would always give a 'nonce invalid' error if the user passed a nonce, even if there was no token at all.

See my fixes to this branch here: https://github.com/eamelink/elm-openid-connect/commit/d114750c72b1ccab028ddc421fbee071b592432a

**Comment by cdevienne** [comment]
Thanks for the feedback!
I will take your commit in my PR

**Comment by cdevienne** [comment]
If everything is fine for your application, I will do a release soon.

**Comment by eamelink** [comment]
Hi, everything works fine! Thanks!

**Pull request merged**
